---
services:
  beets:
    build: .
    container_name: beets
    environment:
      PUID: 1000
      PGID: 1000
      TZ: UTC
    ports:
      - 8337:8337
    volumes:
      - ./config:/config
      - ./data:/data
